name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint and Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Bundle Install
        run: bundle install

      - name: Install Dependencie
        run: ./carthage.sh bootstrap --platform iOS --no-use-binaries --cache-builds

      - name: Run tests
        run: bundle exec fastlane test
